[package]
name = "kubix"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
confy = "0.6"
serde = { version = "1.0", features = ["derive"] }
ctrlc = "3.4"
tabled = "0.15"
owo-colors = "4.0"
